{{- define "shared.service" -}}
{{- $shared := dict "Values" .Values.shared -}}
{{- $isolated := omit .Values "shared" -}}
{{- $overrides := dict "Values" $isolated -}}
{{- $others := omit . "Values" -}}
{{- with merge $others $overrides $shared -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shared.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "shared.name" . }}
    helm.sh/chart: {{ include "shared.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  selector:
    app.kubernetes.io/name: {{ include "shared.name" . }}
{{- end -}}
{{- end -}}