server.port: 7002
server.error.include-message: always

spring:
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      auto-index-creation: true
      authentication-database: admin
      database: review-db

spring.cloud.function.definition: messageProcessor

spring.cloud.stream:
  default.contentType: application/json
  bindings.messageProcessor-in-0:
    destination: reviews
    group: reviewsGroup

spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.kafka.bindings.messageProcessor-in-0.consumer:
  enableDlq: true

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 80
spring.data.mongodb.host: mongodb-1
---
spring.config.activate.on-profile: prod

spring.data.mongodb:
  host: 172.17.0.1
  port: 27018

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG