server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
---
spring.config.activate.on-profile: docker
spring.cloud.stream.kafka.binder.brokers: kafka
---
spring.config.activate.on-profile: kafka
spring.cloud.stream.defaultBinder: kafka
spring.kafka.bootstrap-servers: kafka:9092
spring.cloud.stream.kafka.binder.replication-factor: 1
---
spring.config.activate.on-profile: prod
spring.cloud.stream.kafka.binder.brokers: 172.17.0.1
spring.cloud.stream.kafka.defaultBrokerPort: 9092
spring.cloud.stream.defaultBinder: kafka
spring.cloud.stream.kafka.binder.replication-factor: 1
# Only allow management endpoints over http in production for info, health and circuitbreakerevents
management.endpoints.web.exposure.include: health,info,circuitbreakerevents

